[package]
name = "myxen_presale"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
anchor-lang = "0.27.0"
anchor-spl = "0.27.0"
pyth-client = "0.5"
spl-token = "3.5"
sha2 = "0.10"
ed25519-dalek = "2.0"

[features]
default = ["declare_id"]
